### ISSUE TITLE
[Feat] Login - Social Media (Facebook)

### ISSUE THREAD

**Issue by Hai5edfm** [C10-Ghibli-s/FE-Studio-Ghibli-Tracker#10]
### Summary
At the login screen, the user will be able to login (or register) with his/her Facebook account, therefore we will have a button for each social media. Both are going to redirect our user to its own login which will authenticate the user’s profile and give to us the access token and users info, which will be saved/used to set the username shown in the profile screen.

### Acceptance Criteria [Login button]

- [x] Create component (for each button)

- [x] The component will send a request for login in, in the social media, then, will send to us the access token (confirmation)

- [x] If user is not registered will need to do it (accepting the permissions defined in the register component), we should show an error UI message, this way, the user is going to be able to go back and go to the register page.

- [x] Once logged, we need to bring our user data to load it into the other screens like the [Home page] and [Profile page]

- [x] Test Feature

**Comment by alexcamachogz** [comment]
Pending CSS
