### ISSUE TITLE
[feat] Create Filters Engine

### ISSUE THREAD

**Issue by AreYouIvan** [C10-Ghibli-s/FE-Studio-Ghibli-Tracker#3]
This page must have a filter feature that ables us to define the parameters with which we want the film's information to show to us. This must have a friendly UI.

- [x]  Create the component
- [x]  Build the filter; a function that loops through an array and takes only the items that have the parameters previously defined
- [x]  Connect to API
- [x]  Give and receive the parameters that we want to query
- [x]  Apply styles on the page
- [x]  Test the feature

**Comment by alexcamachogz** [comment]
Testing pending
