### ISSUE TITLE
[feat] Create Search Engine

### ISSUE THREAD

**Issue by AreYouIvan** [C10-Ghibli-s/FE-Studio-Ghibli-Tracker#5]
This page must allow us to make seeks to filter by the title, and also see the results as the user write in the bar. This must have a friendly UI as well.

- [x]  Create the component
- [x]  Build the search engine: A search bar that connects to the API when the user write there and filter with titles matched
- [x]  Integrate an autocomplete feature
- [x]  Make the calls to the API
- [x]  Optimize using debouncing
- [x]  It has styles applied
- [x]  Test the feature

**Comment by alexcamachogz** [comment]
Testing pending
