### ISSUE TITLE
[Feat] Home - Create the card component

### ISSUE THREAD

**Issue by Hai5edfm** [C10-Ghibli-s/FE-Studio-Ghibli-Tracker#7]
### Summary
In order to show each movie with its corresponding Title, Release year, and a brief description to captivate the attention of the user, we need to make a request to the API, then, estructure those fields in a compact card.

### Acceptance Criteria

- [x] Create the component

- [x] Request the necessary information for the fields (Title, Year, Brief description, watched state, rate, poster/image)

- [x] Fill the fields with their corresponding format

- [x] Test the requests and the format(Layout)

**Comment by alexcamachogz** [comment]
Pending CSS
