### ISSUE TITLE
[Feat] Home - Layout / Main section

### ISSUE THREAD

**Issue by Hai5edfm** [C10-Ghibli-s/FE-Studio-Ghibli-Tracker#8]
### Summary
This is the first page the user will view after completing their login/register. There will be two main buttons on top of the page, the first one on the left-top corner; which will take the user to the profile page (where he/she will be able to see another characteristics). On the opposite side, we will have the “Search” button, which will guide our user into the search engine (where will make their requests and even apply some filters and ordering). In the Main section of the page, we will load all the Studio Ghibli Works (component previously created)

### Acceptance Criteria

- [x] Create the nav_Menu component with the two buttons (Profile and search)

- [x] Create a main component which will house the individual components of each card

- [x] Test component

**Comment by AreYouIvan** [comment]
DONE
